[
  {"name": "Invisibles AUG", "worth": 20000, "demand": "2"},
  {"name": "Invisibles RPG", "worth": 18000, "demand": "8"},
  {"name": "Invisibles Barrett", "worth": 17000, "demand": "5"},
  {"name": "Invisibles AS Val", "worth": 15000, "demand": "7"},
  {"name": "Invisibles P90", "worth": 15000, "demand": "7"},
  {"name": "Invisibles Scar", "worth": 15000, "demand": "7"},
  {"name": "Invisibles Riot Shield", "worth": 13000, "demand": "7"},
  {"name": "Invisibles M1", "worth": 9000, "demand": "3"},
  {"name": "Invisibles Flamethrower", "worth": 6000, "demand": "2"},
  {"name": "Invisibles Python", "worth": 5000, "demand": "3"},
  {"name": "Obsidians Minigun", "worth": 15000, "demand": "6"},
  {"name": "Obsidians FNFAL", "worth": 12500, "demand": "8"},
  {"name": "Obsidians RPG", "worth": 12000, "demand": "7.5"},
  {"name": "Obsidians AS Val", "worth": 10000, "demand": "7.5"},
  {"name": "Obsidians AUG", "worth": 9000, "demand": "7"},
  {"name": "Obsidians Barrett", "worth": 9000, "demand": "4"},
  {"name": "Obsidians P90", "worth": 9000, "demand": "7"},
  {"name": "Obsidians Scar", "worth": 7000, "demand": "7"},
  {"name": "Obsidians AK-47", "worth": 6000, "demand": "5"},
  {"name": "Obsidians M1", "worth": 6000, "demand": "6"},
  {"name": "Obsidians M249 SAW", "worth": 6000, "demand": "1"},
  {"name": "Obsidians M4A1", "worth": 6000, "demand": "6"},
  {"name": "Obsidians Tommy Gun", "worth": 6000, "demand": "6"},
  {"name": "Obsidians Double Barrel", "worth": 5000, "demand": "4.5"},
  {"name": "Obsidians Riot Shield", "worth": 5000, "demand": "3.5"},
  {"name": "Obsidians RPK", "worth": 5000, "demand": "3"},
  {"name": "Obsidians Deagle", "worth": 4000, "demand": "3"},
  {"name": "Obsidians Flamethrower", "worth": 4000, "demand": "2"},
  {"name": "Obsidians Raygun", "worth": 4000, "demand": "2"},
  {"name": "Obsidians AR-15", "worth": 3000, "demand": "2"},
  {"name": "Obsidians Python", "worth": 3000, "demand": "3"},
  {"name": "Obsidians M1911", "worth": 2500, "demand": "1"},
  {"name": "Obsidians USP", "worth": 2000, "demand": "1"},
  {"name": "Dark Matter Scar L", "worth": 300, "demand": "8"},
  {"name": "Dark Matter P90", "worth": 260, "demand": "7"},
  {"name": "Dark Matter RPG", "worth": 250, "demand": "6"},
  {"name": "Dark Matter AS Val", "worth": 200, "demand": "6"},
  {"name": "Dark Matter AUG", "worth": 200, "demand": "6.5"},
  {"name": "Dark Matter Barrett M107", "worth": 190, "demand": "4"},
  {"name": "Dark Matter M4A1", "worth": 170, "demand": "5"},
  {"name": "Dark Matter AK-47", "worth": 170, "demand": "4"},
  {"name": "Dark Matter MP7", "worth": 150, "demand": "3"},
  {"name": "Dark Matter Tommy Gun", "worth": 150, "demand": "5"},
  {"name": "Dark Matter Sawn Off", "worth": 140, "demand": "2"},
  {"name": "Dark Matter Double Barrel", "worth": 130, "demand": "2"},
  {"name": "Dark Matter RPK", "worth": 130, "demand": "3"},
  {"name": "Dark Matter M249 SAW", "worth": 125, "demand": "3"},
  {"name": "Dark Matter Deagle", "worth": 120, "demand": "2"},
  {"name": "Dark Matter Python", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Glock", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Glock 18", "worth": 120, "demand": "1"},
  {"name": "Dark Matter M1911", "worth": 120, "demand": "1"},
  {"name": "Dark Matter USP 45", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Mossberg", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Saiga", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Stagecoach", "worth": 120, "demand": "1"},
  {"name": "Dark Matter AR-15", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Uzi", "worth": 120, "demand": "1"},
  {"name": "Dark Matter Dragunov", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Scar L", "worth": 280, "demand": "7.5"},
  {"name": "Anti Matter P90", "worth": 240, "demand": "7"},
  {"name": "Anti Matter RPG", "worth": 230, "demand": "6"},
  {"name": "Anti Matter AS Val", "worth": 180, "demand": "6"},
  {"name": "Anti Matter AUG", "worth": 180, "demand": "6.5"},
  {"name": "Anti Matter Barrett M107", "worth": 170, "demand": "4"},
  {"name": "Anti Matter M4A1", "worth": 150, "demand": "5"},
  {"name": "Anti Matter AK-47", "worth": 150, "demand": "4"},
  {"name": "Anti Matter MP7", "worth": 130, "demand": "3"},
  {"name": "Anti Matter Tommy Gun", "worth": 130, "demand": "4.5"},
  {"name": "Anti Matter Sawn Off", "worth": 120, "demand": "2"},
  {"name": "Anti Matter Double Barrel", "worth": 120, "demand": "2"},
  {"name": "Anti Matter RPK", "worth": 120, "demand": "3"},
  {"name": "Anti Matter M249 SAW", "worth": 120, "demand": "3"},
  {"name": "Anti Matter Deagle", "worth": 120, "demand": "2"},
  {"name": "Anti Matter Python", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Glock", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Glock 18", "worth": 120, "demand": "1"},
  {"name": "Anti Matter M1911", "worth": 120, "demand": "1"},
  {"name": "Anti Matter USP 45", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Mossberg", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Saiga", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Stagecoach", "worth": 120, "demand": "1"},
  {"name": "Anti Matter AR-15", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Uzi", "worth": 120, "demand": "1"},
  {"name": "Anti Matter Dragunov", "worth": 120, "demand": "1"},
  {"name": "Crimson Bloods Scar L", "worth": 320, "demand": "8"},
  {"name": "Crimson Bloods AUG", "worth": 275, "demand": "7.5"},
  {"name": "Crimson Bloods AS Val", "worth": 245, "demand": "7"},
  {"name": "Crimson Bloods M4A1", "worth": 220, "demand": "6.5"},
  {"name": "Crimson Bloods AK-47", "worth": 195, "demand": "5"},
  {"name": "Crimson Bloods Sawn Off", "worth": 170, "demand": "5.5"},
  {"name": "Crimson Bloods Double Barrel", "worth": 155, "demand": "4.5"},
  {"name": "Crimson Bloods RPK", "worth": 150, "demand": "4"},
  {"name": "Crimson Bloods Deagle", "worth": 145, "demand": "3"},
  {"name": "Crimson Bloods Uzi", "worth": 135, "demand": "2"},
  {"name": "Crimson Bloods Glock", "worth": 120, "demand": "1"},
  {"name": "Crimson Bloods Glock 18", "worth": 120, "demand": "1.5"},
  {"name": "Crimson Bloods AR-15", "worth": 120, "demand": "1"},
  {"name": "Void Reapers AS Val", "worth": 250, "demand": "6"},
  {"name": "Void Reapers Reaper Glock", "worth": 120, "demand": "1"},
  {"name": "Underworld Scar L", "worth": 300, "demand": "9"},
  {"name": "Underworld Fn Fal", "worth": 250, "demand": "8.5"},
  {"name": "Underworld RPG", "worth": 250, "demand": "8.5"},
  {"name": "Underworld P90", "worth": 225, "demand": "8"},
  {"name": "Underworld AWP", "worth": 200, "demand": "7"},
  {"name": "Underworld AS Val", "worth": 140, "demand": "8.5"},
  {"name": "Underworld AUG", "worth": 125, "demand": "8"},
  {"name": "Underworld M4A1", "worth": 110, "demand": "7.5"},
  {"name": "Underworld Barrett M107", "worth": 120, "demand": "7"},
  {"name": "Underworld AK-47", "worth": 95, "demand": "6"},
  {"name": "Underworld Tommy Gun", "worth": 90, "demand": "6"},
  {"name": "Underworld M1 Garand", "worth": 85, "demand": "5"},
  {"name": "Underworld Riot Shield", "worth": 80, "demand": "5"},
  {"name": "Underworld RPK", "worth": 70, "demand": "4"},
  {"name": "Underworld MP7", "worth": 60, "demand": "4"},
  {"name": "Underworld M249 SAW", "worth": 55, "demand": "5"},
  {"name": "Underworld Double Barrel", "worth": 65, "demand": "3"},
  {"name": "Underworld Sawn Off", "worth": 70, "demand": "5"},
  {"name": "Underworld AR-15", "worth": 48, "demand": "3"},
  {"name": "Underworld Mossberg", "worth": 48, "demand": "2"},
  {"name": "Underworld Deagle", "worth": 60, "demand": "3"},
  {"name": "Underworld Uzi", "worth": 48, "demand": "2"},
  {"name": "Underworld Python", "worth": 48, "demand": "1"},
  {"name": "Underworld Dragunov", "worth": 48, "demand": "1"},
  {"name": "Underworld Flamethrower", "worth": 50, "demand": "1"},
  {"name": "Underworld Glock", "worth": 48, "demand": "1"},
  {"name": "Underworld Glock 18", "worth": 48, "demand": "1"},
  {"name": "Underworld Stagecoach", "worth": 48, "demand": "1"},
  {"name": "Underworld Saiga 12", "worth": 48, "demand": "1"},
  {"name": "Underworld USP-45", "worth": 48, "demand": "1"},
  {"name": "Underworld Raygun", "worth": 80, "demand": "2"},
  {"name": "Easter Egg RPG", "worth": 175, "demand": "5.5"},
  {"name": "Easter Egg AS Val", "worth": 145, "demand": "4"},
  {"name": "Easter Egg AUG", "worth": 135, "demand": "4.5"},
  {"name": "Easter Egg Barrett", "worth": 125, "demand": "2.5"},
  {"name": "Easter Egg M4A1", "worth": 105, "demand": "4"},
  {"name": "Easter Egg AK-47", "worth": 95, "demand": "2.5"},
  {"name": "Easter Egg Riot Shield", "worth": 95, "demand": "2.5"},
  {"name": "Easter Egg Tommy Gun", "worth": 85, "demand": "3.5"},
  {"name": "Easter Egg MP7", "worth": 50, "demand": "2"},
  {"name": "Easter Egg M249", "worth": 60, "demand": "1.5"},
  {"name": "Easter Egg RPK", "worth": 50, "demand": "1.5"},
  {"name": "Easter Egg Sawn Off", "worth": 55, "demand": "2"},
  {"name": "Easter Egg Double Barrel", "worth": 50, "demand": "1"},
  {"name": "Easter Egg Deagle", "worth": 35, "demand": "1"},
  {"name": "Easter Egg AR-15", "worth": 35, "demand": "1"},
  {"name": "Easter Egg Uzi", "worth": 35, "demand": "1"},
  {"name": "Easter Egg Mossberg", "worth": 30, "demand": "1"},
  {"name": "Easter Egg Stagecoach", "worth": 25, "demand": "1"},
  {"name": "Easter Egg Python", "worth": 20, "demand": "1"},
  {"name": "Easter Egg Dragunov", "worth": 30, "demand": "1"},
  {"name": "Easter Egg Flamethrower", "worth": 40, "demand": "1"},
  {"name": "Easter Egg Saiga 12", "worth": 30, "demand": "1"},
  {"name": "Easter Egg Glock", "worth": 25, "demand": "1"},
  {"name": "Easter Egg Glock 18", "worth": 25, "demand": "1"},
  {"name": "Easter Egg M1991", "worth": 20, "demand": "1"},
  {"name": "Easter Egg USP 45", "worth": 20, "demand": "1"},
  {"name": "Freedom RPG", "worth": 1500, "demand": "8"},
  {"name": "Hotdogs RPG", "worth": 350, "demand": "8"},
  {"name": "Hotdogs AS Val", "worth": 240, "demand": "7"},
  {"name": "Hotdogs AUG", "worth": 230, "demand": "7.5"},
  {"name": "Hotdogs Barrett", "worth": 200, "demand": "5"},
  {"name": "Hotdogs M4A1", "worth": 190, "demand": "6"},
  {"name": "Hotdogs AK-47", "worth": 180, "demand": "5"},
  {"name": "Hotdogs Tommy Gun", "worth": 160, "demand": "6"},
  {"name": "Hotdogs Riot Shield", "worth": 135, "demand": "5"},
  {"name": "Hotdogs MP7", "worth": 130, "demand": "4"},
  {"name": "Hotdogs M249", "worth": 120, "demand": "6"},
  {"name": "Hotdogs RPK", "worth": 135, "demand": "5"},
  {"name": "Hotdogs Sawn Off", "worth": 150, "demand": "6"},
  {"name": "Hotdogs Double Barrel", "worth": 135, "demand": "6"},
  {"name": "Hotdogs Raygun", "worth": 100, "demand": "5"},
  {"name": "Hotdogs AR-15", "worth": 85, "demand": "3"},
  {"name": "Hotdogs Mossberg", "worth": 80, "demand": "2"},
  {"name": "Hotdogs Uzi", "worth": 65, "demand": "2"},
  {"name": "Hotdogs Stagecoach", "worth": 60, "demand": "3"},
  {"name": "Hotdogs Deagle", "worth": 85, "demand": "2"},
  {"name": "Hotdogs Python", "worth": 60, "demand": "1"},
  {"name": "Hotdogs Dragunov", "worth": 60, "demand": "2"},
  {"name": "Hotdogs Flamethrower", "worth": 90, "demand": "1"},
  {"name": "Hotdogs Saiga", "worth": 75, "demand": "1"},
  {"name": "Hotdogs Glock", "worth": 60, "demand": "1"},
  {"name": "Hotdogs Glock 18", "worth": 70, "demand": "1"},
  {"name": "Hotdogs M1991", "worth": 65, "demand": "1"},
  {"name": "Hotdogs USP 45", "worth": 60, "demand": "1"},
  {"name": "White RPG", "worth": 180, "demand": "9"},
  {"name": "White AS Val", "worth": 170, "demand": "8.5"},
  {"name": "White AUG", "worth": 160, "demand": "8.5"},
  {"name": "White Barrett", "worth": 140, "demand": "7"},
  {"name": "White M4A1", "worth": 110, "demand": "6"},
  {"name": "White AK-47", "worth": 90, "demand": "5"},
  {"name": "White Tommy Gun", "worth": 80, "demand": "6"},
  {"name": "White Riot Shield", "worth": 100, "demand": "5"},
  {"name": "White MP7", "worth": 70, "demand": "5"},
  {"name": "White M249", "worth": 60, "demand": "4"},
  {"name": "White RPK", "worth": 50, "demand": "4"},
  {"name": "White Sawn Off", "worth": 60, "demand": "5"},
  {"name": "White Double Barrel", "worth": 40, "demand": "3"},
  {"name": "White AR-15", "worth": 20, "demand": "2"},
  {"name": "White Mossberg", "worth": 20, "demand": "2"},
  {"name": "White Uzi", "worth": 15, "demand": "1"},
  {"name": "White Stagecoach", "worth": 10, "demand": "1"},
  {"name": "White Deagle", "worth": 30, "demand": "2"},
  {"name": "White Python", "worth": 15, "demand": "1"},
  {"name": "White Dragunov", "worth": 10, "demand": "1"},
  {"name": "White Flamethrower", "worth": 15, "demand": "1"},
  {"name": "White Saiga 12", "worth": 10, "demand": "1"},
  {"name": "White Glock", "worth": 10, "demand": "1"},
  {"name": "White Glock 18", "worth": 15, "demand": "1"},
  {"name": "White M1911", "worth": 10, "demand": "1"},
  {"name": "White USP 45", "worth": 10, "demand": "1"},
  {"name": "White Raygun", "worth": 40, "demand": "2"},
  {"name": "Red RPG", "worth": 150, "demand": "9"},
  {"name": "Red AS Val", "worth": 130, "demand": "8"},
  {"name": "Red AUG", "worth": 125, "demand": "8.5"},
  {"name": "Red Barrett", "worth": 110, "demand": "8"},
  {"name": "Red M4A1", "worth": 100, "demand": "7.5"},
  {"name": "Red AK-47", "worth": 90, "demand": "7"},
  {"name": "Red Tommy Gun", "worth": 90, "demand": "7"},
  {"name": "Red Riot Shield", "worth": 95, "demand": "5"},
  {"name": "Red MP7", "worth": 50, "demand": "6"},
  {"name": "Red M249", "worth": 45, "demand": "4"},
  {"name": "Red RPK", "worth": 40, "demand": "4"},
  {"name": "Red Sawn Off", "worth": 50, "demand": "6"},
  {"name": "Red Double Barrel", "worth": 45, "demand": "5"},
  {"name": "Red AR-15", "worth": 20, "demand": "2"},
  {"name": "Red Mossberg", "worth": 20, "demand": "2"},
  {"name": "Red Uzi", "worth": 10, "demand": "1"},
  {"name": "Red Stagecoach", "worth": 10, "demand": "1"},
  {"name": "Red Deagle", "worth": 30, "demand": "3"},
  {"name": "Red Python", "worth": 10, "demand": "2"},
  {"name": "Red Dragunov", "worth": 10, "demand": "1"},
  {"name": "Red Flamethrower", "worth": 10, "demand": "1"},
  {"name": "Red Saiga 12", "worth": 10, "demand": "1"},
  {"name": "Red Glock", "worth": 15, "demand": "2"},
  {"name": "Red Glock 18", "worth": 15, "demand": "2"},
  {"name": "Red M1911", "worth": 10, "demand": "1"},
  {"name": "Red USP 45", "worth": 10, "demand": "1"},
  {"name": "Red Raygun", "worth": 30, "demand": "3"},
  {"name": "Blue RPG", "worth": 150, "demand": "9"},
  {"name": "Blue AS Val", "worth": 130, "demand": "8"},
  {"name": "Blue AUG", "worth": 125, "demand": "8.5"},
  {"name": "Blue Barrett", "worth": 110, "demand": "8"},
  {"name": "Blue M4A1", "worth": 100, "demand": "7.5"},
  {"name": "Blue AK-47", "worth": 90, "demand": "7"},
  {"name": "Blue Tommy Gun", "worth": 90, "demand": "7"},
  {"name": "Blue Riot Shield", "worth": 95, "demand": "5"},
  {"name": "Blue MP7", "worth": 50, "demand": "6"},
  {"name": "Blue M249", "worth": 45, "demand": "4"},
  {"name": "Blue RPK", "worth": 40, "demand": "4"},
  {"name": "Blue Sawn Off", "worth": 50, "demand": "6"},
  {"name": "Blue Double Barrel", "worth": 45, "demand": "5"},
  {"name": "Blue AR-15", "worth": 20, "demand": "2"},
  {"name": "Blue Mossberg", "worth": 20, "demand": "2"},
  {"name": "Blue Uzi", "worth": 10, "demand": "1"},
  {"name": "Blue Stagecoach", "worth": 10, "demand": "1"},
  {"name": "Blue Deagle", "worth": 30, "demand": "3"},
  {"name": "Blue Python", "worth": 10, "demand": "2"},
  {"name": "Blue Dragunov", "worth": 10, "demand": "1"},
  {"name": "Blue Flamethrower", "worth": 10, "demand": "1"},
  {"name": "Blue Saiga 12", "worth": 10, "demand": "1"},
  {"name": "Blue Glock", "worth": 15, "demand": "2"},
  {"name": "Blue Glock 18", "worth": 15, "demand": "2"},
  {"name": "Blue M1911", "worth": 10, "demand": "1"},
  {"name": "Blue USP 45", "worth": 10, "demand": "1"},
  {"name": "Blue Raygun", "worth": 30, "demand": "3"},
  {"name": "USA RPG", "worth": 100, "demand": "9"},
  {"name": "USA AS Val", "worth": 90, "demand": "8"},
  {"name": "USA AUG", "worth": 85, "demand": "8"},
  {"name": "USA Barrett", "worth": 70, "demand": "7"},
  {"name": "USA M4A1", "worth": 65, "demand": "6"},
  {"name": "USA AK-47", "worth": 50, "demand": "5.5"},
  {"name": "USA Tommy Gun", "worth": 40, "demand": "5"},
  {"name": "USA Riot Shield", "worth": 45, "demand": "4"},
  {"name": "USA MP7", "worth": 40, "demand": "5"},
  {"name": "USA M249", "worth": 30, "demand": "4"},
  {"name": "USA RPK", "worth": 25, "demand": "4"},
  {"name": "USA Sawn Off", "worth": 35, "demand": "5"},
  {"name": "USA Double Barrel", "worth": 30, "demand": "4.5"},
  {"name": "USA AR-15", "worth": 20, "demand": "3"},
  {"name": "USA Mossberg", "worth": 15, "demand": "3"},
  {"name": "USA Uzi", "worth": 10, "demand": "1"},
  {"name": "USA Stagecoach", "worth": 8, "demand": "1"},
  {"name": "USA Deagle", "worth": 10, "demand": "2"},
  {"name": "USA Python", "worth": 7, "demand": "1"},
  {"name": "USA Dragunov", "worth": 5, "demand": "1"},
  {"name": "USA Flamethrower", "worth": 15, "demand": "1"},
  {"name": "USA Saiga 12", "worth": 10, "demand": "1"},
  {"name": "USA Glock", "worth": 5, "demand": "1"},
  {"name": "USA Glock 18", "worth": 10, "demand": "1"},
  {"name": "USA M1991", "worth": 5, "demand": "1"},
  {"name": "USA USP 45", "worth": 5, "demand": "1"},
  {"name": "USA Raygun", "worth": 20, "demand": "3"},
  {"name": "Firework RPG", "worth": 85, "demand": "9"},
  {"name": "Firework AS Val", "worth": 75, "demand": "8"},
  {"name": "Firework AUG", "worth": 70, "demand": "7"},
  {"name": "Firework Barrett", "worth": 60, "demand": "6"},
  {"name": "Firework M4A1", "worth": 55, "demand": "5.5"},
  {"name": "Firework AK-47", "worth": 45, "demand": "5"},
  {"name": "Firework Tommy Gun", "worth": 35, "demand": "5"},
  {"name": "Firework Riot Shield", "worth": 30, "demand": "4"},
  {"name": "Firework MP7", "worth": 35, "demand": "5"},
  {"name": "Firework M249", "worth": 30, "demand": "4"},
  {"name": "Firework RPK", "worth": 30, "demand": "4"},
  {"name": "Firework Sawn Off", "worth": 40, "demand": "4"},
  {"name": "Firework Double Barrel", "worth": 25, "demand": "3"},
  {"name": "Firework AR-15", "worth": 20, "demand": "1"},
  {"name": "Firework Mossberg", "worth": 15, "demand": "2"},
  {"name": "Firework Uzi", "worth": 8, "demand": "1"},
  {"name": "Firework Stagecoach", "worth": 7, "demand": "1"},
  {"name": "Firework Deagle", "worth": 10, "demand": "1"},
  {"name": "Firework Python", "worth": 5, "demand": "1"},
  {"name": "Firework Dragunov", "worth": 5, "demand": "1"},
  {"name": "Firework Flamethrower", "worth": 10, "demand": "2"},
  {"name": "Firework Saiga 12", "worth": 7, "demand": "1"},
  {"name": "Firework Glock", "worth": 4, "demand": "1"},
  {"name": "Firework Glock 18", "worth": 8, "demand": "1"},
  {"name": "Firework M1991", "worth": 5, "demand": "1"},
  {"name": "Firework USP 45", "worth": 5, "demand": "1"},
  {"name": "Firework Raygun", "worth": 25, "demand": "2.5"},
  {"name": "Starry RPG", "worth": 80, "demand": "9"},
  {"name": "Starry AS Val", "worth": 75, "demand": "8.5"},
  {"name": "Starry AUG", "worth": 70, "demand": "8"},
  {"name": "Starry Barrett", "worth": 60, "demand": "7"},
  {"name": "Starry M4A1", "worth": 50, "demand": "6.5"},
  {"name": "Starry AK-47", "worth": 40, "demand": "6"},
  {"name": "Starry Tommy Gun", "worth": 35, "demand": "5.5"},
  {"name": "Starry Riot Shield", "worth": 30, "demand": "5"},
  {"name": "Starry MP7", "worth": 40, "demand": "5"},
  {"name": "Starry M249", "worth": 30, "demand": "4"},
  {"name": "Starry RPK", "worth": 35, "demand": "4"},
  {"name": "Starry Sawn Off", "worth": 40, "demand": "5"},
  {"name": "Starry Double Barrel", "worth": 30, "demand": "3"},
  {"name": "Starry AR-15", "worth": 15, "demand": "2"},
  {"name": "Starry Mossberg", "worth": 15, "demand": "2"},
  {"name": "Starry Uzi", "worth": 7, "demand": "1"},
  {"name": "Starry Stagecoach", "worth": 7, "demand": "1"},
  {"name": "Starry Deagle", "worth": 10, "demand": "2"},
  {"name": "Starry Python", "worth": 8, "demand": "1"},
  {"name": "Starry Dragunov", "worth": 5, "demand": "1"},
  {"name": "Starry Flamethrower", "worth": 15, "demand": "1.5"},
  {"name": "Starry Saiga 12", "worth": 7, "demand": "1"},
  {"name": "Starry Glock", "worth": 5, "demand": "1"},
  {"name": "Starry Glock 18", "worth": 8, "demand": "1"},
  {"name": "Starry M1991", "worth": 5, "demand": "1"},
  {"name": "Starry USP 45", "worth": 5, "demand": "1"},
  {"name": "Starry Raygun", "worth": 20, "demand": "2"},
  {"name": "Pumpkin RPG", "worth": 900, "demand": "9.5"},
  {"name": "Skin Melter Double Barrel", "worth": 425, "demand": "5.5"},
  {"name": "Skin Melter Mossberg", "worth": 325, "demand": "3"},
  {"name": "Halloween 2023 SCAR-L", "worth": 235, "demand": "8"},
  {"name": "Halloween 2023 RPG", "worth": 200, "demand": "8"},
  {"name": "Halloween 2023 AS Val", "worth": 180, "demand": "8.5"},
  {"name": "Halloween 2023 AUG", "worth": 150, "demand": "7.5"},
  {"name": "Halloween 2023 M4A1", "worth": 110, "demand": "6"},
  {"name": "Halloween 2023 Barrett", "worth": 100, "demand": "6"},
  {"name": "Halloween 2023 AK-47", "worth": 90, "demand": "5"},
  {"name": "Halloween 2023 Tommy Gun", "worth": 80, "demand": "7"},
  {"name": "Halloween 2023 Riot Shield", "worth": 100, "demand": "3"},
  {"name": "Halloween 2023 RPK", "worth": 80, "demand": "6"},
  {"name": "Halloween 2023 MP7", "worth": 75, "demand": "6.5"},
  {"name": "Halloween 2023 M249 Saw", "worth": 80, "demand": "5"},
  {"name": "Halloween 2023 Double Barrel", "worth": 75, "demand": "6"},
  {"name": "Halloween 2023 Sawn Off", "worth": 75, "demand": "6"},
  {"name": "Halloween 2023 AR-15", "worth": 50, "demand": "3"},
  {"name": "Halloween 2023 Mossberg", "worth": 50, "demand": "2"},
  {"name": "Halloween 2023 Deagle", "worth": 70, "demand": "4"},
  {"name": "Halloween 2023 Uzi", "worth": 65, "demand": "3"},
  {"name": "Halloween 2023 Python", "worth": 48, "demand": "1"},
  {"name": "Halloween 2023 Dragunov", "worth": 48, "demand": "1"},
  {"name": "Halloween 2023 Flamethrower", "worth": 90, "demand": "3"},
  {"name": "Halloween 2023 Glock", "worth": 60, "demand": "2"},
  {"name": "Halloween 2023 Glock 18", "worth": 60, "demand": "2"},
  {"name": "Halloween 2023 Stagecoach", "worth": 50, "demand": "1"},
  {"name": "Halloween 2023 Saiga 12", "worth": 48, "demand": "1"},
  {"name": "Halloween 2023 USP45", "worth": 48, "demand": "1"},
  {"name": "Halloween 2023 Raygun", "worth": 80, "demand": "5"},
  {"name": "Toys AUG", "worth": 1800, "demand": "10"},
  {"name": "Toys AS Val", "worth": 850, "demand": "8"},
  {"name": "Toys Barrett M107", "worth": 670, "demand": "7"},
  {"name": "Toys Deagle", "worth": 580, "demand": "6"},
  {"name": "Toys Minigun", "worth": 600, "demand": "6"},
  {"name": "Toys Tommy Gun", "worth": 520, "demand": "7.5"},
  {"name": "Toys AK-47", "worth": 530, "demand": "6"},
  {"name": "Toys MP7", "worth": 510, "demand": "6.5"},
  {"name": "Toys Double Barrel", "worth": 440, "demand": "5"},
  {"name": "Toys Sawn Off", "worth": 500, "demand": "6"},
  {"name": "Toys M249 Saw", "worth": 400, "demand": "4"},
  {"name": "Toys RPK", "worth": 360, "demand": "5"},
  {"name": "Toys Mossberg", "worth": 300, "demand": "3"},
  {"name": "Toys Python", "worth": 270, "demand": "2"},
  {"name": "Cursed Pumpkin RPG", "worth": 500, "demand": "6"},
  {"name": "Void Reaper Barrett M107", "worth": 200, "demand": "4.5"},
  {"name": "Void Reaper M4A1", "worth": 225, "demand": "5.5"},
  {"name": "Void Reaper AK 47", "worth": 210, "demand": "5"},
  {"name": "Skelly Barrett M107", "worth": 50, "demand": "4"},
  {"name": "Skelly P90", "worth": 60, "demand": "5"},
  {"name": "White Ghost P90", "worth": 70, "demand": "6"},
  {"name": "White Ghost Scar L", "worth": 80, "demand": "6.5"},
  {"name": "White Ghost RPG", "worth": 75, "demand": "6"},
  {"name": "White Ghost AS Val", "worth": 70, "demand": "5.5"},
  {"name": "White Ghost AUG", "worth": 65, "demand": "5"},
  {"name": "White Ghost Barrett", "worth": 55, "demand": "4"},
  {"name": "White Ghost M4A1", "worth": 52, "demand": "4"},
  {"name": "White Ghost AK 47", "worth": 50, "demand": "3.5"},
  {"name": "White Ghost Tommy Gun", "worth": 48, "demand": "3"},
  {"name": "White Ghost Riot Shield", "worth": 45, "demand": "6"},
  {"name": "White Ghost MP7", "worth": 45, "demand": "3"},
  {"name": "White Ghost M249", "worth": 42, "demand": "2.5"},
  {"name": "White Ghost RPK", "worth": 40, "demand": "3"},
  {"name": "White Ghost Sawn Off", "worth": 45, "demand": "3.5"},
  {"name": "White Ghost Minigun", "worth": 40, "demand": "3"},
  {"name": "White Ghost Double Barrel", "worth": 40, "demand": "2.5"},
  {"name": "White Ghost AR-15", "worth": 35, "demand": "1"},
  {"name": "White Ghost Mossberg", "worth": 35, "demand": "1"},
  {"name": "White Ghost Uzi", "worth": 28, "demand": "1"},
  {"name": "White Ghost Stagecoach", "worth": 32, "demand": "0"},
  {"name": "White Ghost Deagle", "worth": 35, "demand": "2"},
  {"name": "White Ghost Python", "worth": 30, "demand": "0.5"},
  {"name": "White Ghost Dragunov", "worth": 30, "demand": "0"},
  {"name": "White Ghost Flamethrower", "worth": 35, "demand": "2"},
  {"name": "White Ghost Saiga 12", "worth": 30, "demand": "1"},
  {"name": "White Ghost Glock", "worth": 27, "demand": "0"},
  {"name": "White Ghost Glock 18", "worth": 30, "demand": "0.5"},
  {"name": "White Ghost M1991", "worth": 25, "demand": "0"},
  {"name": "White Ghost USP 45", "worth": 24, "demand": "0"},
  {"name": "White Ghost Raygun", "worth": 40, "demand": "2.5"},
  {"name": "Solid Gold Scar", "worth": 700, "demand": "8.5"},
  {"name": "Solid Gold AUG", "worth": 575, "demand": "7.5"},
  {"name": "Solid Gold AS Val", "worth": 550, "demand": "7"},
  {"name": "Solid Gold Barrett", "worth": 460, "demand": "5.5"},
  {"name": "Solid Gold AK 47", "worth": 375, "demand": "5"},
  {"name": "Solid Gold MP7", "worth": 350, "demand": "6"},
  {"name": "Solid Gold M249 Saw", "worth": 300, "demand": "4"},
  {"name": "Solid Gold Dragunov", "worth": 220, "demand": "1.5"},
  {"name": "Solid Gold Glock 18", "worth": 190, "demand": "1"},
  {"name": "Solid Gold Glock", "worth": 170, "demand": "1"},
  {"name": "Gift Wrapped RPG", "worth": 550, "demand": "8"},
  {"name": "Gift Wrapped P90", "worth": 400, "demand": "6.5"},
  {"name": "Gift Wrapped AS Val", "worth": 445, "demand": "7"},
  {"name": "Gift Wrapped AUG", "worth": 440, "demand": "8"},
  {"name": "Gift Wrapped Barrett", "worth": 350, "demand": "6"},
  {"name": "Gift Wrapped AK 47", "worth": 325, "demand": "6"},
  {"name": "Gift Wrapped Tommy Gun", "worth": 300, "demand": "6"},
  {"name": "Gift Wrapped RPK", "worth": 280, "demand": "5"},
  {"name": "Gift Wrapped Sawn Off", "worth": 270, "demand": "6"},
  {"name": "Gift Wrapped Minigun", "worth": 320, "demand": "6"},
  {"name": "Gift Wrapped Double Barrel", "worth": 250, "demand": "4.5"},
  {"name": "Gift Wrapped Mossberg", "worth": 190, "demand": "2"},
  {"name": "Gift Wrapped Deagle", "worth": 210, "demand": "3"},
  {"name": "Gift Wrapped Python", "worth": 160, "demand": "1"},
  {"name": "Christmas Future Scar L", "worth": 420, "demand": "7"},
  {"name": "Christmas Future Barrett", "worth": 360, "demand": "6.5"},
  {"name": "Christmas Future AK47", "worth": 320, "demand": "5"},
  {"name": "Christmas Future Mossberg", "worth": 240, "demand": "2"},
  {"name": "Christmas Future Python", "worth": 180, "demand": "1.5"},
  {"name": "Golden Snow RPG", "worth": 375, "demand": "7"},
  {"name": "Golden Snow Scar L", "worth": 310, "demand": "6.5"},
  {"name": "Golden Snow AUG", "worth": 260, "demand": "6"},
  {"name": "Golden Snow P90", "worth": 200, "demand": "5"},
  {"name": "Golden Snow MP7", "worth": 150, "demand": "5.5"},
  {"name": "Sub Zero Scar L", "worth": 60, "demand": "2"},
  {"name": "Sub Zero Garand", "worth": 30, "demand": "1.5"},
  {"name": "Frozen Gold Scar L", "worth": 350, "demand": "8"},
  {"name": "Frozen Gold Garand", "worth": 200, "demand": "7"},
  {"name": "Rainbow Firework RPG", "worth": 450, "demand": "7"},
  {"name": "Solid Gold V2 P90", "worth": 280, "demand": "5"},
  {"name": "Solid Gold V2 RPG", "worth": 320, "demand": "6.5"},
  {"name": "Solid Gold V2 FN Fal", "worth": 300, "demand": "6"},
  {"name": "Solid Gold V2 AWP", "worth": 260, "demand": "5"},
  {"name": "Solid Gold V2 M1 Garand", "worth": 250, "demand": "4"},
  {"name": "Solid Gold V2 RPK", "worth": 220, "demand": "3"},
  {"name": "Solid Gold V2 Deagle", "worth": 180, "demand": "3"},
  {"name": "St Patrick Tommy Gun", "worth": 850, "demand": "7"},
  {"name": "St Patrick Python", "worth": 400, "demand": "3.5"},
  {"name": "Holy Fire AS Val", "worth": 250, "demand": "5.5"},
  {"name": "Holy Fire M4A1", "worth": 180, "demand": "4"},
  {"name": "Holy Fire Barrett M107", "worth": 170, "demand": "3"},
  {"name": "Holy Fire AK 47", "worth": 160, "demand": "5"},
  {"name": "Holy Fire Glock", "worth": 75, "demand": "1"},
  {"name": "Bloody Heart AS Val", "worth": 230, "demand": "7.5"},
  {"name": "Bloody Heart Tommy Gun", "worth": 190, "demand": "6.5"},
  {"name": "Bloody Heart Barrett M107", "worth": 160, "demand": "5.5"},
  {"name": "Bloody Heart Uzi", "worth": 110, "demand": "4"},
  {"name": "Bloody Heart Python", "worth": 70, "demand": "3"},
  {"name": "Fallout RPG", "worth": 215, "demand": "6"},
  {"name": "Fallout P90", "worth": 200, "demand": "6.5"},
  {"name": "Fallout M249 SAW", "worth": 120, "demand": "5"},
  {"name": "Fallout Barrett M107", "worth": 110, "demand": "3"},
  {"name": "Fallout M1911", "worth": 35, "demand": "1"},
  {"name": "Atomic Pumpkin RPG", "worth": 450, "demand": "9"},
  {"name": "Atomic Pumpkin AS Val", "worth": 400, "demand": "8.5"},
  {"name": "Atomic Pumpkin M4A1", "worth": 350, "demand": "7"},
  {"name": "Atomic Pumpkin Sawn Off", "worth": 230, "demand": "6"},
  {"name": "Atomic Pumpkin Double Barrel", "worth": 200, "demand": "5.5"},
  {"name": "Ethereal Scar L", "worth": 320, "demand": "9"},
  {"name": "Ethereal M4A1", "worth": 240, "demand": "7"},
  {"name": "Ethereal RPK", "worth": 180, "demand": "6"},
  {"name": "Ethereal AK 47", "worth": 160, "demand": "5"},
  {"name": "Ethereal AR 15", "worth": 145, "demand": "4.5"},
  {"name": "Ethereal Double Barrel", "worth": 135, "demand": "5.5"},
  {"name": "Ethereal Sawn Off", "worth": 130, "demand": "5"},
  {"name": "Ethereal Uzi", "worth": 115, "demand": "4"},
  {"name": "Ethereal Deagle", "worth": 110, "demand": "4"},
  {"name": "Ethereal AUG", "worth": 70, "demand": "3"},
  {"name": "Ethereal AS Val", "worth": 65, "demand": "3"},
  {"name": "Ethereal Glock 18", "worth": 55, "demand": "2"},
  {"name": "Ethereal Glock", "worth": 45, "demand": "1"},
  {"name": "Ethereal M1911", "worth": 35, "demand": "1"},
  {"name": "Spectral Scar L", "worth": 300, "demand": "8.5"},
  {"name": "Spectral FN FAL", "worth": 235, "demand": "7"},
  {"name": "Spectral RPG", "worth": 270, "demand": "8"},
  {"name": "Spectral AUG", "worth": 240, "demand": "7.5"},
  {"name": "Spectral AS Val", "worth": 230, "demand": "7"},
  {"name": "Spectral P90", "worth": 190, "demand": "6.5"},
  {"name": "Spectral MP7", "worth": 175, "demand": "6"},
  {"name": "Spectral Barrett M107", "worth": 165, "demand": "5.5"},
  {"name": "Spectral AWP", "worth": 160, "demand": "5"},
  {"name": "Spectral AK 47", "worth": 145, "demand": "5"},
  {"name": "Spectral M1 Garand", "worth": 130, "demand": "4.5"},
  {"name": "Spectral RPK", "worth": 120, "demand": "5.5"},
  {"name": "Spectral M249 SAW", "worth": 105, "demand": "4"},
  {"name": "Spectral Deagle", "worth": 90, "demand": "4"},
  {"name": "Spectral Dragunov", "worth": 80, "demand": "3.5"},
  {"name": "Spectral Glock 18", "worth": 60, "demand": "2"},
  {"name": "Spectral Glock", "worth": 40, "demand": "1"},
  {"name": "Balloons Dollar", "worth": 14000, "demand": "9"},
  {"name": "Balloons Heart", "worth": 850, "demand": "8"},
  {"name": "Balloons Clover", "worth": 750, "demand": "8"},
  {"name": "Balloons Ghost", "worth": 500, "demand": "7"},
  {"name": "Balloons Bunny", "worth": 300, "demand": "5"},
  {"name": "Balloons Bat", "worth": 250, "demand": "4"},
  {"name": "Balloons Skull", "worth": 200, "demand": "3"},
  {"name": "Balloons Gold Rose", "worth": 2000, "demand": "10"},
  {"name": "Balloons Void Rose", "worth": 15000, "demand": "10+"}
]
